<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
class products extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('products')->insert([
            ['name' => 'IPhone 15 Pro Max 128GB', 'slug' =>'ao-vcl', 'amount' => 32900000, 'price' => 28900000, 'image' =>'iphone_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 Pro Max 256GB', 'slug' =>'ao-vcl', 'amount' => 32500000, 'price' => 25900000, 'image' =>'iphone_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 Pro Max 512GB', 'slug' =>'ao-vcl', 'amount' => 31900000, 'price' => 26900000, 'image' =>'iphone_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 Pro Max 1T', 'slug' =>'ao-vcl', 'amount' => 35900000, 'price' => 31900000, 'image' =>'iphone_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 Pro 128GB', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 21900000, 'image' =>'iphone_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 Pro 256GB', 'slug' =>'ao-vcl', 'amount' => 28500000, 'price' => 25900000, 'image' =>'iphone_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 Pro 512GB', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 26900000, 'image' =>'iphone_06.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 Pro 1T', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 26900000, 'image' =>'iphone_07.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 128GB', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 14900000, 'image' =>'iphone_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 256GB', 'slug' =>'ao-vcl', 'amount' => 23500000, 'price' => 13900000, 'image' =>'iphone_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 512GB', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 11900000, 'image' =>'iphone_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 1T', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 11900000, 'image' =>'iphone_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 mini 128GB', 'slug' =>'ao-vcl', 'amount' => 18900000, 'price' => 14900000, 'image' =>'iphone_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 mini 256GB', 'slug' =>'ao-vcl', 'amount' => 18500000, 'price' => 12800000, 'image' =>'iphone_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 mini 512GB', 'slug' =>'ao-vcl', 'amount' => 18900000, 'price' => 12900000, 'image' =>'iphone_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 15 mini 1T', 'slug' =>'ao-vcl', 'amount' => 18900000, 'price' => 14900000, 'image' =>'iphone_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '1', 'category_id'=>1, 'created_at' => now()],

            ['name' => 'IPhone 14 Pro Max 128GB', 'slug' =>'ao-vcl', 'amount' => 32900000, 'price' => 28900000, 'image' =>'iphone_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 14 Pro Max 256GB', 'slug' =>'ao-vcl', 'amount' => 32500000, 'price' => 25900000, 'image' =>'iphone_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 14 Pro Max 512GB', 'slug' =>'ao-vcl', 'amount' => 31900000, 'price' => 26900000, 'image' =>'iphone_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 14 Pro Max 1T', 'slug' =>'ao-vcl', 'amount' => 35900000, 'price' => 31900000, 'image' =>'iphone_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 14 Pro 128GB', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 21900000, 'image' =>'iphone_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 14 Pro 256GB', 'slug' =>'ao-vcl', 'amount' => 28500000, 'price' => 25900000, 'image' =>'iphone_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 14 Pro 512GB', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 26900000, 'image' =>'iphone_06.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 14 Pro 1T', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 26900000, 'image' =>'iphone_07.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 14 128GB', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 14900000, 'image' =>'iphone_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 14 256GB', 'slug' =>'ao-vcl', 'amount' => 23500000, 'price' => 13900000, 'image' =>'iphone_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 14 512GB', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 11900000, 'image' =>'iphone_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 14 1T', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 11900000, 'image' =>'iphone_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '2', 'category_id'=>1, 'created_at' => now()],

            ['name' => 'IPhone 13 Pro Max 123GB', 'slug' =>'ao-vcl', 'amount' => 32900000, 'price' => 23900000, 'image' =>'iphone_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 13 Pro Max 256GB', 'slug' =>'ao-vcl', 'amount' => 32500000, 'price' => 25900000, 'image' =>'iphone_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 13 Pro Max 512GB', 'slug' =>'ao-vcl', 'amount' => 31900000, 'price' => 26900000, 'image' =>'iphone_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 13 Pro Max 1T', 'slug' =>'ao-vcl', 'amount' => 35900000, 'price' => 31900000, 'image' =>'iphone_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 13 Pro 128GB', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 21900000, 'image' =>'iphone_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 13 Pro 256GB', 'slug' =>'ao-vcl', 'amount' => 28500000, 'price' => 25900000, 'image' =>'iphone_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 13 Pro 512GB', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 26900000, 'image' =>'iphone_06.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 13 Pro 1T', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 26900000, 'image' =>'iphone_07.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 13 128GB', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 14900000, 'image' =>'iphone_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 13 256GB', 'slug' =>'ao-vcl', 'amount' => 23500000, 'price' => 13900000, 'image' =>'iphone_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 13 512GB', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 11900000, 'image' =>'iphone_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 13 1T', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 11900000, 'image' =>'iphone_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '3', 'category_id'=>1, 'created_at' => now()],

            ['name' => 'IPhone 12 Pro Max 128GB', 'slug' =>'ao-vcl', 'amount' => 32900000, 'price' => 28900000, 'image' =>'iphone_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '4', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 12 Pro Max 256GB', 'slug' =>'ao-vcl', 'amount' => 32500000, 'price' => 25900000, 'image' =>'iphone_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '4', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 12 Pro Max 512GB', 'slug' =>'ao-vcl', 'amount' => 31900000, 'price' => 26900000, 'image' =>'iphone_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '4', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 12 Pro 128GB', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 21900000, 'image' =>'iphone_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '4', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 12 Pro 256GB', 'slug' =>'ao-vcl', 'amount' => 28500000, 'price' => 25900000, 'image' =>'iphone_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '4', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 12 Pro 512GB', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 26900000, 'image' =>'iphone_06.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '4', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 12 128GB', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 14900000, 'image' =>'iphone_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '4', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 12 256GB', 'slug' =>'ao-vcl', 'amount' => 23500000, 'price' => 13900000, 'image' =>'iphone_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '4', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 12 512GB', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 11900000, 'image' =>'iphone_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '4', 'category_id'=>1, 'created_at' => now()],

            ['name' => 'IPhone 11 Pro Max 128GB', 'slug' =>'ao-vcl', 'amount' => 32900000, 'price' => 28900000, 'image' =>'iphone_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '5', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 11 Pro Max 256GB', 'slug' =>'ao-vcl', 'amount' => 32500000, 'price' => 25900000, 'image' =>'iphone_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '5', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 11 Pro Max 512GB', 'slug' =>'ao-vcl', 'amount' => 31900000, 'price' => 26900000, 'image' =>'iphone_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '5', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 11 Pro 128GB', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 21900000, 'image' =>'iphone_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '5', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 11 Pro 256GB', 'slug' =>'ao-vcl', 'amount' => 28500000, 'price' => 25900000, 'image' =>'iphone_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '5', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 11 Pro 512GB', 'slug' =>'ao-vcl', 'amount' => 28900000, 'price' => 26900000, 'image' =>'iphone_06.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '5', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 11 128GB', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 14900000, 'image' =>'iphone_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '5', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 11 256GB', 'slug' =>'ao-vcl', 'amount' => 23500000, 'price' => 13900000, 'image' =>'iphone_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '5', 'category_id'=>1, 'created_at' => now()],
            ['name' => 'IPhone 11 512GB', 'slug' =>'ao-vcl', 'amount' => 23900000, 'price' => 11900000, 'image' =>'iphone_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>0, 'model_id' => '5', 'category_id'=>1, 'created_at' => now()],

            ['name' => 'iPad Pro M1 12.9 inch WiFi Cellular 512GB', 'slug' =>'ao-vcl', 'amount' => 42990000, 'price' => 32900000, 'image' =>'ipad_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '6', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Pro M1 12.9 inch WiFi 512GB', 'slug' =>'ao-vcl', 'amount' => 38990000, 'price' => 29900000, 'image' =>'ipad_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '6', 'category_id'=>2, 'created_at' => now()],

            ['name' => 'iPad Pro M2 11 inch WiFi 128GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 19900000, 'image' =>'ipad_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '7', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Pro M2 11 inch WiFi Cellular 128GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 23900000, 'image' =>'ipad_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '7', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Pro M2 12.9 inch WiFi 128GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 23900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '7', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Pro M2 11 inch WiFi Cellular 256GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 21900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '7', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Pro M2 11 inch WiFi 256GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 22900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '7', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Pro M2 11 inch WiFi 512GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 23900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '7', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Pro M2 12.9 inch WiFi Cellular 128GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 26900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '7', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Pro M2 12.9 inch WiFi Cellular 258GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 23900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '7', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Pro M2 12.9 inch WiFi Cellular 512GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 23700000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '7', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Pro M2 12.9 inch WiFi Cellular 1TB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 21900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '7', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Pro M2 12.9 inch WiFi Cellular 2TB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 25900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '7', 'category_id'=>2, 'created_at' => now()],

            ['name' => 'iPad Air 4', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 15900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '8', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Air 5 WiFi 64GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 12900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '8', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Air 5 WiFi 256GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 16900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '8', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Air 5 WiFi Cellular 64GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 25900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '8', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Air 5 WiFi Cellular 256GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 22900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '8', 'category_id'=>2, 'created_at' => now()],

            ['name' => 'iPad gen 9 10.2 inch WiFi 64GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 22900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '9', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Gen 9th 10.2 inch WiFi 256GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 22900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '9', 'category_id'=>2, 'created_at' => now()],

            ['name' => 'iPad Gen 10 th 10.9 inch WiFi 64GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 22900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '10', 'category_id'=>2, 'created_at' => now()],
            ['name' => 'iPad Gen 10th 10.9 inch WiFi Cellular 64GB', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 22900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '10', 'category_id'=>2, 'created_at' => now()],

            ['name' => 'iPad Mini 6', 'slug' =>'ao-vcl', 'amount' => 28990000, 'price' => 22900000, 'image' =>'ipad_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '11', 'category_id'=>2, 'created_at' => now()],

            ['name' => 'MacBook Pro 16 M1 Pro (16 Core/16GB/1TB)', 'slug' =>'ao-vcl', 'amount' => 48990000, 'price' => 43900000, 'image' =>'mac_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '12', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'MacBook Pro 13 inch M2 (10 core| 8GB RAM| 256GB SSD)', 'slug' =>'ao-vcl', 'amount' => 43990000, 'price' => 38900000, 'image' =>'mac_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '12', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'MacBook Pro 16 M1 Pro (16 Core/16GB/512SSD)', 'slug' =>'ao-vcl', 'amount' => 43990000, 'price' => 38900000, 'image' =>'mac_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '12', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'MacBook Pro 13 inch M2 (10 core| 16GB RAM| 512GB SSD)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 32900000, 'image' =>'mac_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '12', 'category_id'=>3, 'created_at' => now()],

            ['name' => 'MacBook Pro 14 inch M3 2023 (8GB RAM| 10 Core GPU| 512GB SSD)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 32900000, 'image' =>'mac_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '13', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'MacBook Pro 14 inch M3 2023 (8GB RAM| 10 Core GPU| 1TB SSD)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 32900000, 'image' =>'mac_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '13', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'MacBook Pro 14 inch M3 Pro 2023 (18GB RAM| 14 core GPU| 512GB SSD)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 32900000, 'image' =>'mac_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '13', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'MacBook Pro 14 inch M3 Pro 2023 (18GB RAM| 18 core GPU| 1TB SSD)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 32900000, 'image' =>'mac_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '13', 'category_id'=>3, 'created_at' => now()],

            ['name' => 'MacBook Air M1 2020 (8GB RAM | 256GB SSD)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 32900000, 'image' =>'mac_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '14', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'MacBook Air M3 13 inch', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 32900000, 'image' =>'mac_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '14', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'MacBook Air M2 2022 (8GB RAM | 256GB SSD)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 28900000, 'image' =>'mac_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '14', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'MacBook Air M2 2022 (8GB RAM | 512GB SSD)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 29900000, 'image' =>'mac_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '14', 'category_id'=>3, 'created_at' => now()],

            ['name' => 'iMac M1 2021 24 inch (8 Core GPU/8GB/512GB)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 29900000, 'image' =>'mac_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '15', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'iMac M3 2023 24 inch (8 Core GPU/8GB/256GB)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 29900000, 'image' =>'mac_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '15', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'iMac M3 2023 24 inch (10 Core GPU/8GB/256GB)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 29900000, 'image' =>'mac_06.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '15', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'iMac M3 2023 24 inch (10 Core GPU/8GB/512GB)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 28900000, 'image' =>'mac_07.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '15', 'category_id'=>3, 'created_at' => now()],
            
            ['name' => 'Mac mini M2 (10-Core GPU| 8GB RAM | 256GB SSD)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 28900000, 'image' =>'mac_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '16', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'Mac mini M2 (10-Core GPU| 8GB RAM | 512GB SSD)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 27900000, 'image' =>'mac_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '16', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'Mac mini M2 Pro (16-Core GPU| 16GB RAM | 512GB SSD)', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 24900000, 'image' =>'mac_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '16', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'Mac mini M2 (10-Core GPU| 16GB RAM | 256GB SSD) CTO', 'slug' =>'ao-vcl', 'amount' => 33990000, 'price' => 23900000, 'image' =>'mac_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '16', 'category_id'=>3, 'created_at' => now()],

            ['name' => 'Mac Pro M2 Ultra', 'slug' =>'ao-vcl', 'amount' => 200990000, 'price' => 199900000, 'image' =>'mac_07.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '17', 'category_id'=>3, 'created_at' => now()],

            ['name' => 'Studio Display', 'slug' =>'ao-vcl', 'amount' => 20990000, 'price' => 19900000, 'image' =>'mac_07.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '18', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'Mac Studio M1 Max', 'slug' =>'ao-vcl', 'amount' => 50990000, 'price' => 49900000, 'image' =>'mac_07.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '18', 'category_id'=>3, 'created_at' => now()],
            ['name' => 'Mac Studio M1 Ultra', 'slug' =>'ao-vcl', 'amount' => 109990000, 'price' => 99900000, 'image' =>'mac_07.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '18', 'category_id'=>3, 'created_at' => now()],

            ['name' => 'Apple Watch Ultra 2 GPS + Cellular 49mm Ocean Band', 'slug' =>'ao-vcl', 'amount' => 5990000, 'price' => 5200000, 'image' =>'watch_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '19', 'category_id'=>4, 'created_at' => now()],
            ['name' => 'Apple Watch Ultra 2 GPS + Cellular 49mm Alpine LoopS', 'slug' =>'ao-vcl', 'amount' => 2790000, 'price' => 20900000, 'image' =>'watch_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '19', 'category_id'=>4, 'created_at' => now()],
            ['name' => 'Apple Watch Ultra 2 GPS + Cellular 49mm Trail Loop', 'slug' =>'ao-vcl', 'amount' => 6990000, 'price' => 5900000, 'image' =>'watch_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '19', 'category_id'=>4, 'created_at' => now()],
            ['name' => 'Apple Watch Series 9 Nhôm (GPS + Cellular) 41mm | Sport Band', 'slug' =>'ao-vcl', 'amount' => 1290000, 'price' => 10900000, 'image' =>'watch_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '19', 'category_id'=>4, 'created_at' => now()],
            
            ['name' => 'Apple Watch Series 9 Nhôm (GPS) 41mm | Sport Band', 'slug' =>'ao-vcl', 'amount' => 9790000, 'price' => 7900000, 'image' =>'watch_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '20', 'category_id'=>4, 'created_at' => now()],
            ['name' => 'Apple Watch Series 9 Nhôm (GPS) 41mm | Sport Loop', 'slug' =>'ao-vcl', 'amount' => 9790000, 'price' => 8900000, 'image' =>'watch_06.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '20', 'category_id'=>4, 'created_at' => now()],
            ['name' => 'Apple Watch Series 9 Nhôm (GPS) 45mm | Sport Band', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10900000, 'image' =>'watch_05.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '20', 'category_id'=>4, 'created_at' => now()],
            ['name' => 'Apple Watch Series 9 Nhôm (GPS) 45mm | Sport Loop', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'watch_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '20', 'category_id'=>4, 'created_at' => now()],
            
            ['name' => 'Apple Watch Series 8 Nhôm (GPS) 45mm | Sport Loop', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'watch_06.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '21', 'category_id'=>4, 'created_at' => now()],
            
            ['name' => 'Apple Watch SE 2023 GPS Sport Loop', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'watch_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '21', 'category_id'=>4, 'created_at' => now()],

            ['name' => 'Apple Watch Series 7 Nhôm GPS', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'watch_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '22', 'category_id'=>4, 'created_at' => now()],
            ['name' => 'Apple Watch Series 7 Thép GPS + Cellular', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'watch_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '22', 'category_id'=>4, 'created_at' => now()],

            ['name' => 'Apple Watch Series 6 Thép GPS + Cellular', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'watch_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '23', 'category_id'=>4, 'created_at' => now()],
            
            ['name' => 'Apple Watch Series 3 Nhôm', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'watch_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '24', 'category_id'=>4, 'created_at' => now()],

            ['name' => 'Loa Marshall Acton II Bluetooth', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'sound_01.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '25', 'category_id'=>5, 'created_at' => now()],
            ['name' => 'Loa Marshall Stanmore II Bluetooth', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'sound_02.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '25', 'category_id'=>5, 'created_at' => now()],

            ['name' => 'Tai nghe Apple WH1000XM5', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'sound_03.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '26', 'category_id'=>5, 'created_at' => now()],
            ['name' => 'Loa Harman Kardon Onyx Studio 8', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'sound_04.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '26', 'category_id'=>5, 'created_at' => now()],

            ['name' => 'AirPos 2', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'sound_06.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '27', 'category_id'=>5, 'created_at' => now()],
            ['name' => 'AirPos 3', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'sound_07.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '27', 'category_id'=>5, 'created_at' => now()],
            ['name' => 'AirPos Pro', 'slug' =>'ao-vcl', 'amount' => 12790000, 'price' => 10700000, 'image' =>'sound_09.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '27', 'category_id'=>5, 'created_at' => now()],

            ['name' => 'AirPos Pro', 'slug' =>'ao-vcl', 'amount' => 1279000, 'price' => 1070000, 'image' =>'sound_09.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '28', 'category_id'=>6, 'created_at' => now()],
            ['name' => 'Cường lực', 'slug' =>'ao-vcl', 'amount' => 1290000, 'price' => 1070000, 'image' =>'sound_09.png', 'thumbnails'=>'iphone_01.png', 'description' => 'abc', 'shortDes' =>'abc', 'hot'=>1, 'model_id' => '29', 'category_id'=>6, 'created_at' => now()],



        ]);
    }
}
